// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRl15cPavGIQwG86bO4CiOkXZErTgu-q8',
    appId: '1:1023699257272:web:64c02837bf6ca9dd06314d',
    messagingSenderId: '1023699257272',
    projectId: 'buku-tamu-467c6',
    authDomain: 'buku-tamu-467c6.firebaseapp.com',
    storageBucket: 'buku-tamu-467c6.firebasestorage.app',
    measurementId: 'G-REZKG2SEL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWL3Yvs7AcrAqfd4eke0phcvjRjl6V4nA',
    appId: '1:1023699257272:android:b68427599182043806314d',
    messagingSenderId: '1023699257272',
    projectId: 'buku-tamu-467c6',
    storageBucket: 'buku-tamu-467c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbD4jAjGmdYofLQYjFK6-SsbhDlxW12ik',
    appId: '1:1023699257272:ios:beb18773ab0a0c2d06314d',
    messagingSenderId: '1023699257272',
    projectId: 'buku-tamu-467c6',
    storageBucket: 'buku-tamu-467c6.firebasestorage.app',
    iosBundleId: 'com.example.bukuTamu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbD4jAjGmdYofLQYjFK6-SsbhDlxW12ik',
    appId: '1:1023699257272:ios:beb18773ab0a0c2d06314d',
    messagingSenderId: '1023699257272',
    projectId: 'buku-tamu-467c6',
    storageBucket: 'buku-tamu-467c6.firebasestorage.app',
    iosBundleId: 'com.example.bukuTamu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRl15cPavGIQwG86bO4CiOkXZErTgu-q8',
    appId: '1:1023699257272:web:a605ed9b4213a18606314d',
    messagingSenderId: '1023699257272',
    projectId: 'buku-tamu-467c6',
    authDomain: 'buku-tamu-467c6.firebaseapp.com',
    storageBucket: 'buku-tamu-467c6.firebasestorage.app',
    measurementId: 'G-3YH6DT4EYD',
  );
}
